export const TIME_SERIES_INTRADAY = "TIME_SERIES_INTRADAY";
export const TIME_SERIES_DAILY = "TIME_SERIES_DAILY";
export const TIME_SERIES_DAILY_ADJUSTED = "TIME_SERIES_DAILY_ADJUSTED";
export const TIME_SERIES_WEEKLY = "TIME_SERIES_WEEKLY";
export const TIME_SERIES_WEEKLY_ADJUSTED = "TIME_SERIES_WEEKLY_ADJUSTED";
